name: New Issue

on:
  issues:
    types:
      - opened

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Issue comment
        uses: GrantBirki/comment@v2.0.10
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ github.event.issue.number }}
          body: Thanks for opening an issue!
